spring:
  application:
    name: REST-APIS

  server:
    port:8080

  datasource:
    driver-class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/training 
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update